application: cold-turkey
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /_ah/spi/.*
  script: scheduleslist_api.application
- url: /.*
  script: addschedule.application

libraries:
- name: pycrypto
  version: latest
- name: endpoints
  version: 1.0
